[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "dpm-teach"
version = "0.0.1"
description = "Tutorial notebooks for Digital Rock Physics. To be used with Digital Porous Media Portal"
authors = [
  { name="Bernard Chang", email="bcchang@utexas.edu" }
]
license = { text = "MIT" }
readme = "README.md"
requires-python = ">=3.9"

dependencies = [
    "numpy",
    "matplotlib",
    "scikit-image",
    "plotly",
    "requests",
    "tifffile",
    "pandas",
    "dpm-tools"
]

[project.optional-dependencies]
chapter1 = ["medpy"]
chapter2 = ["medpy"]
chapter3 = ["pyvista[all]", "porespy", "trimesh", "connected-components-3d", "networkx", "edt"]
chapter4 = ["pyvista[all]"]
chapter5 = ["openpnm", "porespy"]
chapter6 = ["torch"]
all = ["medpy", "pyvista[all]", "porespy", "trimesh", "connected-components-3d", "networkx", "edt", "openpnm", "torch"]

[tool.setuptools.packages.find]
where = ["."]
include = ["utils"]
